<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BigGustave" Version="1.0.6" />
      <PackageReference Include="MeltySynth" Version="2.4.1" />
      <PackageReference Include="NAudio.WaveFormRenderer" Version="2.0.0" />
      <PackageReference Include="Ps2IsoTools" Version="1.1.2" />
      <PackageReference Include="Syroot.BinaryData" Version="5.2.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SoundFont2\SoundFont2\SoundFont2.csproj" />
    </ItemGroup>

</Project>
