<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ApplicationIcon>Assets\F.ico</ApplicationIcon>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <PublishAot>true</PublishAot>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.4" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.17" />
        <PackageReference Include="NetCoreAudio" Version="2.0.1" />
        <PackageReference Include="OpenTK" Version="4.9.4" />
        <PackageReference Include="OpenTK.Graphics" Version="4.9.4" />
        <PackageReference Include="OpenTKAvalonia" Version="1.0.0" />
        <PackageReference Include="SukiUI" Version="7.0.1" />

        <ProjectReference Include="..\FlipnicLib\FlipnicLib.csproj" />
    </ItemGroup>
  <ItemGroup>
    <None Remove=".gitignore" />
  </ItemGroup>
    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>
    <ItemGroup>
      <Compile Update="Controls\MessageEditor.axaml.cs">
        <DependentUpon>MessageEditor.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Controls\MenuMockup.axaml.cs">
        <DependentUpon>MenuMockup.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Controls\CLIBox.axaml.cs">
        <DependentUpon>CLIBox.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Controls\CircleDot.axaml.cs">
        <DependentUpon>CircleDot.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Controls\CameraTool.axaml.cs">
        <DependentUpon>CameraTool.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
