<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ApplicationIcon>Assets\F.ico</ApplicationIcon>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.6" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.6" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.1.5" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.6" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.6" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.6" />
        <PackageReference Include="NetCoreAudio" Version="2.0.0" />
        <PackageReference Include="OpenTK" Version="4.9.4" />
        <PackageReference Include="OpenTK.Graphics" Version="4.9.4" />
        <PackageReference Include="OpenTKAvalonia" Version="1.0.0" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
        <PackageReference Include="SukiUI" Version="6.0.3" />

        <ProjectReference Include="..\FlipnicLib\FlipnicLib.csproj" />
    </ItemGroup>
  <ItemGroup>
    <None Remove=".gitignore" />
    <None Update="Shaders\shader.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Shaders\shader.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>
</Project>
